import 'package:flutter/material.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;

// User Model
class User {
  final int id;
  final String name;
  final String email;

  User({required this.id, required this.name, required this.email});

  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['id'],
      name: json['name'],
      email: json['email'],
    );
  }
}

// API Service
class ApiService {
  Future<List<User>> fetchUsers() async {
    final response =
        await http.get(Uri.parse('https://jsonplaceholder.typicode.com/users'));

    if (response.statusCode == 200) {
      List<dynamic> data = json.decode(response.body);

      data = [
        {"id": 1, "name": "Megen", "email": "Jumont"},
        {"id": 2, "name": "Karena", "email": "Ridings"},
        {"id": 3, "name": "Delaney", "email": "Domb"},
        {"id": 4, "name": "Robyn", "email": "Kiessel"},
        {"id": 5, "name": "Felicle", "email": "Pappi"},
        {"id": 6, "name": "Matteo", "email": "Hunton"},
        {"id": 7, "name": "Ethelyn", "email": "Labell"},
        {"id": 8, "name": "Rakel", "email": "Whiteoak"},
        {"id": 9, "name": "Guilbert", "email": "Cruft"},
        {"id": 10, "name": "Grantham", "email": "Chelam"},
        {"id": 11, "name": "Pier", "email": "O'Shields"},
        {"id": 12, "name": "Dominic", "email": "Giacomozzo"},
        {"id": 13, "name": "Barde", "email": "Leirmonth"},
        {"id": 14, "name": "Filbert", "email": "Calterone"},
        {"id": 15, "name": "Candida", "email": "Trenholme"},
        {"id": 16, "name": "Cynthy", "email": "Leicester"},
        {"id": 17, "name": "Micheil", "email": "Dedham"},
        {"id": 18, "name": "Rolland", "email": "O'Luney"},
        {"id": 19, "name": "Frederica", "email": "Lortz"},
        {"id": 20, "name": "Kasey", "email": "Ruffli"},
        {"id": 21, "name": "Rodger", "email": "Lestor"},
        {"id": 22, "name": "Ralph", "email": "Allner"},
        {"id": 23, "name": "Con", "email": "Robertelli"},
        {"id": 24, "name": "Yorgos", "email": "Cuming"},
        {"id": 25, "name": "Camala", "email": "Standing"},
        {"id": 26, "name": "Johna", "email": "Blasik"},
        {"id": 27, "name": "Allyce", "email": "Plenty"},
        {"id": 28, "name": "Meris", "email": "Bromet"},
        {"id": 29, "name": "Issy", "email": "Santo"},
        {"id": 30, "name": "Marve", "email": "Greg"},
        {"id": 31, "name": "Margalit", "email": "Shortcliffe"},
        {"id": 32, "name": "Tommy", "email": "Sellwood"},
        {"id": 33, "name": "Ashla", "email": "Sinyard"},
        {"id": 34, "name": "Rufus", "email": "Saben"},
        {"id": 35, "name": "Wade", "email": "Authers"},
        {"id": 36, "name": "Randall", "email": "Andrioli"},
        {"id": 37, "name": "Willa", "email": "Baldacchi"},
        {"id": 38, "name": "Lynda", "email": "Suermeier"},
        {"id": 39, "name": "Simone", "email": "Mees"},
        {"id": 40, "name": "Gusti", "email": "Coupland"},
        {"id": 41, "name": "Pearline", "email": "Richardet"},
        {"id": 42, "name": "Uta", "email": "Allnatt"},
        {"id": 43, "name": "Johann", "email": "Reder"},
        {"id": 44, "name": "Eugenius", "email": "Barkes"},
        {"id": 45, "name": "Raynell", "email": "Fike"},
        {"id": 46, "name": "Angele", "email": "Marvelley"},
        {"id": 47, "name": "Harmonia", "email": "Pattingson"},
        {"id": 48, "name": "Patric", "email": "Rickerd"},
        {"id": 49, "name": "Greggory", "email": "Kleisel"},
        {"id": 50, "name": "Coralyn", "email": "Shorland"},
        {"id": 51, "name": "Pyotr", "email": "Baugham"},
        {"id": 52, "name": "Lenore", "email": "Spelman"},
        {"id": 53, "name": "Emilia", "email": "Pree"},
        {"id": 54, "name": "Emile", "email": "Laingmaid"},
        {"id": 55, "name": "Morgan", "email": "Medwell"},
        {"id": 56, "name": "Tabby", "email": "Fink"},
        {"id": 57, "name": "Sal", "email": "Ody"},
        {"id": 58, "name": "Conan", "email": "Radmer"},
        {"id": 59, "name": "Charmain", "email": "Sparway"},
        {"id": 60, "name": "Brianne", "email": "Jager"},
        {"id": 61, "name": "Liuka", "email": "Edmott"},
        {"id": 62, "name": "Cob", "email": "Lancashire"},
        {"id": 63, "name": "Matthieu", "email": "Berard"},
        {"id": 64, "name": "Carson", "email": "Lowers"},
        {"id": 65, "name": "Jarad", "email": "Beadell"},
        {"id": 66, "name": "Athena", "email": "Skehan"},
        {"id": 67, "name": "Chad", "email": "Skirvane"},
        {"id": 68, "name": "Conrado", "email": "Elintune"},
        {"id": 69, "name": "Collie", "email": "Brasener"},
        {"id": 70, "name": "Leroy", "email": "Wooding"},
        {"id": 71, "name": "Heddie", "email": "Gartland"},
        {"id": 72, "name": "Sherie", "email": "Vanlint"},
        {"id": 73, "name": "Arluene", "email": "Pumfrey"},
        {"id": 74, "name": "Shelley", "email": "Kippling"},
        {"id": 75, "name": "Natalee", "email": "Chinnock"},
        {"id": 76, "name": "Gare", "email": "Davidof"},
        {"id": 77, "name": "Robina", "email": "Kabos"},
        {"id": 78, "name": "Stormie", "email": "Swinnard"},
        {"id": 79, "name": "Panchito", "email": "McSharry"},
        {"id": 80, "name": "Carley", "email": "Mains"},
        {"id": 81, "name": "Cornelle", "email": "Brellin"},
        {"id": 82, "name": "Winfred", "email": "Ettles"},
        {"id": 83, "name": "Nolly", "email": "Guerrin"},
        {"id": 84, "name": "Cele", "email": "Grinter"},
        {"id": 85, "name": "Audre", "email": "Jerzyk"},
        {"id": 86, "name": "Scott", "email": "Vonderdell"},
        {"id": 87, "name": "Ardys", "email": "Beebis"},
        {"id": 88, "name": "Mariana", "email": "Chatelet"},
        {"id": 89, "name": "Collete", "email": "Paskins"},
        {"id": 90, "name": "Marvin", "email": "Gonthier"},
        {"id": 91, "name": "Duffy", "email": "Goadsby"},
        {"id": 92, "name": "Leena", "email": "Elcocks"},
        {"id": 93, "name": "Uriel", "email": "Date"},
        {"id": 94, "name": "Silas", "email": "Kinder"},
        {"id": 95, "name": "Eda", "email": "Mattityahou"},
        {"id": 96, "name": "Meier", "email": "Nisby"},
        {"id": 97, "name": "Mahala", "email": "Dibsdale"},
        {"id": 98, "name": "Jethro", "email": "Kilborn"},
        {"id": 99, "name": "Farr", "email": "Addison"},
        {"id": 100, "name": "Garey", "email": "Herity"},
        {"id": 101, "name": "Tyrone", "email": "King"},
        {"id": 102, "name": "Marji", "email": "Prine"},
        {"id": 103, "name": "Cami", "email": "Mathelin"},
        {"id": 104, "name": "Domeniga", "email": "Taw"},
        {"id": 105, "name": "Darnall", "email": "Canner"},
        {"id": 106, "name": "Katy", "email": "Munton"},
        {"id": 107, "name": "Fair", "email": "Aish"},
        {"id": 108, "name": "Marmaduke", "email": "Rubenchik"},
        {"id": 109, "name": "Katee", "email": "Danilovic"},
        {"id": 110, "name": "Bess", "email": "Harnor"},
        {"id": 111, "name": "Claudelle", "email": "Querree"},
        {"id": 112, "name": "Inez", "email": "Anderton"},
        {"id": 113, "name": "Anabel", "email": "Batterham"},
        {"id": 114, "name": "Edmund", "email": "Eggins"},
        {"id": 115, "name": "Ivett", "email": "Durie"},
        {"id": 116, "name": "William", "email": "Wiggam"},
        {"id": 117, "name": "Isa", "email": "Gusney"},
        {"id": 118, "name": "Isidora", "email": "Syddie"},
        {"id": 119, "name": "Delbert", "email": "Bracknell"},
        {"id": 120, "name": "Yetty", "email": "Yeowell"},
        {"id": 121, "name": "Sanford", "email": "Mattevi"},
        {"id": 122, "name": "Julia", "email": "Brotheridge"},
        {"id": 123, "name": "Marchall", "email": "Jays"},
        {"id": 124, "name": "Nessy", "email": "Bowry"},
        {"id": 125, "name": "Casi", "email": "Leefe"},
        {"id": 126, "name": "Kirstyn", "email": "Wickson"},
        {"id": 127, "name": "Nat", "email": "Soughton"},
        {"id": 128, "name": "Clerc", "email": "Heddy"},
        {"id": 129, "name": "Shae", "email": "Grazier"},
        {"id": 130, "name": "Andy", "email": "Bottjer"},
        {"id": 131, "name": "Wallie", "email": "Gurner"},
        {"id": 132, "name": "Odell", "email": "Timberlake"},
        {"id": 133, "name": "Jo-anne", "email": "Sloley"},
        {"id": 134, "name": "Dyanne", "email": "Rozenzweig"},
        {"id": 135, "name": "Adela", "email": "Atwater"},
        {"id": 136, "name": "Christa", "email": "Cordeux"},
        {"id": 137, "name": "Stevy", "email": "Van der Linde"},
        {"id": 138, "name": "Ronnie", "email": "Ottee"},
        {"id": 139, "name": "Alisun", "email": "Sawl"},
        {"id": 140, "name": "Missy", "email": "Grand"},
        {"id": 141, "name": "Wynn", "email": "Stare"},
        {"id": 142, "name": "Wayland", "email": "Postans"},
        {"id": 143, "name": "Roselia", "email": "Gumey"},
        {"id": 144, "name": "Debbie", "email": "O'Gorman"},
        {"id": 145, "name": "Waylon", "email": "Brewers"},
        {"id": 146, "name": "Viki", "email": "Kinane"},
        {"id": 147, "name": "Greg", "email": "Lathleiffure"},
        {"id": 148, "name": "Abbie", "email": "Muzzi"},
        {"id": 149, "name": "Doris", "email": "Hartland"},
        {"id": 150, "name": "Jorie", "email": "Buddleigh"},
        {"id": 151, "name": "Nicholas", "email": "Lyal"},
        {"id": 152, "name": "Case", "email": "Townley"},
        {"id": 153, "name": "Margalit", "email": "Matveyev"},
        {"id": 154, "name": "Cybil", "email": "Tembey"},
        {"id": 155, "name": "Quinlan", "email": "Ouslem"},
        {"id": 156, "name": "Ainslie", "email": "Sorensen"},
        {"id": 157, "name": "Sheffield", "email": "Basillon"},
        {"id": 158, "name": "Alanah", "email": "Glassopp"},
        {"id": 159, "name": "Debra", "email": "Rops"},
        {"id": 160, "name": "Kim", "email": "Adamovicz"},
        {"id": 161, "name": "Tobe", "email": "de Werk"},
        {"id": 162, "name": "Leora", "email": "Elderton"},
        {"id": 163, "name": "Gisella", "email": "Message"},
        {"id": 164, "name": "Faun", "email": "Nutkin"},
        {"id": 165, "name": "Arlin", "email": "Arkell"},
        {"id": 166, "name": "Tuck", "email": "Dundendale"},
        {"id": 167, "name": "Kellyann", "email": "Eldrid"},
        {"id": 168, "name": "Giles", "email": "Ayllett"},
        {"id": 169, "name": "Zorana", "email": "Mathiot"},
        {"id": 170, "name": "Lydia", "email": "Hanson"},
        {"id": 171, "name": "Robb", "email": "Droogan"},
        {"id": 172, "name": "Perry", "email": "Wegman"},
        {"id": 173, "name": "Hildegarde", "email": "Laugharne"},
        {"id": 174, "name": "Lockwood", "email": "Evered"},
        {"id": 175, "name": "Julianne", "email": "Mitford"},
        {"id": 176, "name": "Malia", "email": "Avrahm"},
        {"id": 177, "name": "Kathleen", "email": "Loidl"},
        {"id": 178, "name": "Wilhelm", "email": "Blackshaw"},
        {"id": 179, "name": "Barr", "email": "Trollope"},
        {"id": 180, "name": "Iormina", "email": "Demange"},
        {"id": 181, "name": "Rayshell", "email": "McLaverty"},
        {"id": 182, "name": "Suzette", "email": "McKerron"},
        {"id": 183, "name": "Felicity", "email": "Mulligan"},
        {"id": 184, "name": "Tadeas", "email": "Drinkhall"},
        {"id": 185, "name": "Dulcinea", "email": "Grimston"},
        {"id": 186, "name": "Archambault", "email": "Lealle"},
        {"id": 187, "name": "Arlinda", "email": "Gonet"},
        {"id": 188, "name": "Pamella", "email": "Dunbobin"},
        {"id": 189, "name": "Ardith", "email": "Crose"},
        {"id": 190, "name": "Rosina", "email": "Runnett"},
        {"id": 191, "name": "Antonius", "email": "Janaway"},
        {"id": 192, "name": "Randie", "email": "Lambricht"},
        {"id": 193, "name": "Waldo", "email": "Jolley"},
        {"id": 194, "name": "Carolynn", "email": "Leggan"},
        {"id": 195, "name": "Amalle", "email": "Broome"},
        {"id": 196, "name": "Dean", "email": "Egiloff"},
        {"id": 197, "name": "Jess", "email": "Leedal"},
        {"id": 198, "name": "Sib", "email": "Duligall"},
        {"id": 199, "name": "Sig", "email": "Landy"},
        {"id": 200, "name": "Renie", "email": "Leftley"},
        {"id": 201, "name": "Harri", "email": "Cawdell"},
        {"id": 202, "name": "Brynn", "email": "Camier"},
        {"id": 203, "name": "Rubi", "email": "Spaule"},
        {"id": 204, "name": "Claretta", "email": "Sturges"},
        {"id": 205, "name": "Ambrosi", "email": "McRinn"},
        {"id": 206, "name": "Dayle", "email": "Vannoni"},
        {"id": 207, "name": "Bordie", "email": "Thormann"},
        {"id": 208, "name": "Siegfried", "email": "Patterfield"},
        {"id": 209, "name": "Michaelina", "email": "Strand"},
        {"id": 210, "name": "Claudine", "email": "Manuel"},
        {"id": 211, "name": "Thomasina", "email": "Bernardin"},
        {"id": 212, "name": "Von", "email": "Borton"},
        {"id": 213, "name": "Ruben", "email": "Skitch"},
        {"id": 214, "name": "Josee", "email": "Fairfoull"},
        {"id": 215, "name": "Fan", "email": "Rowledge"},
        {"id": 216, "name": "Calhoun", "email": "Crux"},
        {"id": 217, "name": "Emilie", "email": "Einchcombe"},
        {"id": 218, "name": "Genna", "email": "Eva"},
        {"id": 219, "name": "Annice", "email": "Mandre"},
        {"id": 220, "name": "Carrie", "email": "Gossan"},
        {"id": 221, "name": "Edmund", "email": "Rooney"},
        {"id": 222, "name": "Emmit", "email": "Dyshart"},
        {"id": 223, "name": "Myrtle", "email": "Leneve"},
        {"id": 224, "name": "Myrtle", "email": "Khomishin"},
        {"id": 225, "name": "Siobhan", "email": "Titley"},
        {"id": 226, "name": "Madelyn", "email": "Pattie"},
        {"id": 227, "name": "Wash", "email": "Di Carlo"},
        {"id": 228, "name": "Tansy", "email": "Impy"},
        {"id": 229, "name": "Vaughn", "email": "Tommeo"},
        {"id": 230, "name": "Minni", "email": "MacKeogh"},
        {"id": 231, "name": "Deane", "email": "Killigrew"},
        {"id": 232, "name": "Hi", "email": "Sycamore"},
        {"id": 233, "name": "Nari", "email": "Aronoff"},
        {"id": 234, "name": "Patsy", "email": "Phizackarley"},
        {"id": 235, "name": "Karney", "email": "Bonellie"},
        {"id": 236, "name": "Austina", "email": "Kensington"},
        {"id": 237, "name": "Simon", "email": "Knewstub"},
        {"id": 238, "name": "Luise", "email": "Aslie"},
        {"id": 239, "name": "Yoshiko", "email": "Blase"},
        {"id": 240, "name": "Reinald", "email": "Gokes"},
        {"id": 241, "name": "Rasia", "email": "Pauler"},
        {"id": 242, "name": "Deidre", "email": "Gyves"},
        {"id": 243, "name": "Corbet", "email": "Brody"},
        {"id": 244, "name": "Delphinia", "email": "Sterke"},
        {"id": 245, "name": "Ashley", "email": "Arcase"},
        {"id": 246, "name": "Marie-ann", "email": "Harborow"},
        {"id": 247, "name": "Poppy", "email": "Laskey"},
        {"id": 248, "name": "Algernon", "email": "Chilver"},
        {"id": 249, "name": "Olivie", "email": "Bagnal"},
        {"id": 250, "name": "Constanta", "email": "Malcolm"},
        {"id": 251, "name": "Georgena", "email": "Neale"},
        {"id": 252, "name": "Orrin", "email": "Tomsa"},
        {"id": 253, "name": "Mureil", "email": "Abercrombie"},
        {"id": 254, "name": "Dania", "email": "Reid"},
        {"id": 255, "name": "Winnah", "email": "Catlette"},
        {"id": 256, "name": "Felice", "email": "Camies"},
        {"id": 257, "name": "Annecorinne", "email": "Kalb"},
        {"id": 258, "name": "Winni", "email": "Wheal"},
        {"id": 259, "name": "Mab", "email": "Felmingham"},
        {"id": 260, "name": "Pru", "email": "Landreth"},
        {"id": 261, "name": "Haily", "email": "Ballaam"},
        {"id": 262, "name": "Netta", "email": "Grasner"},
        {"id": 263, "name": "Zachary", "email": "Papa"},
        {"id": 264, "name": "Pierre", "email": "Fane"},
        {"id": 265, "name": "Rosemonde", "email": "Ouslem"},
        {"id": 266, "name": "Gabriellia", "email": "Branscomb"},
        {"id": 267, "name": "Dulcinea", "email": "Bayliss"},
        {"id": 268, "name": "Kaleena", "email": "Rehm"},
        {"id": 269, "name": "Bradley", "email": "Jaquiss"},
        {"id": 270, "name": "Elonore", "email": "Darko"},
        {"id": 271, "name": "Cynde", "email": "Brannigan"},
        {"id": 272, "name": "Phylys", "email": "McChesney"},
        {"id": 273, "name": "Bride", "email": "Oswell"},
        {"id": 274, "name": "Kippar", "email": "Sterman"},
        {"id": 275, "name": "Christina", "email": "Attersoll"},
        {"id": 276, "name": "Simonne", "email": "Cowherd"},
        {"id": 277, "name": "Tait", "email": "Gilmore"},
        {"id": 278, "name": "Murielle", "email": "Corradeschi"},
        {"id": 279, "name": "Nell", "email": "Orringe"},
        {"id": 280, "name": "Loreen", "email": "Mathiasen"},
        {"id": 281, "name": "Coretta", "email": "Kayzer"},
        {"id": 282, "name": "Tuck", "email": "Bayman"},
        {"id": 283, "name": "Kiri", "email": "Stokey"},
        {"id": 284, "name": "Nikki", "email": "Armour"},
        {"id": 285, "name": "Fiona", "email": "Tanslie"},
        {"id": 286, "name": "Ruthi", "email": "Broek"},
        {"id": 287, "name": "Hilton", "email": "Glawsop"},
        {"id": 288, "name": "Josee", "email": "Greves"},
        {"id": 289, "name": "Miguela", "email": "Swapp"},
        {"id": 290, "name": "Elliott", "email": "Denholm"},
        {"id": 291, "name": "Willie", "email": "Dangerfield"},
        {"id": 292, "name": "Derrick", "email": "Gebby"},
        {"id": 293, "name": "Justinian", "email": "Petriello"},
        {"id": 294, "name": "Nessa", "email": "Gilliat"},
        {"id": 295, "name": "Clea", "email": "Hinzer"},
        {"id": 296, "name": "Datha", "email": "Thurske"},
        {"id": 297, "name": "Doralia", "email": "Schuricht"},
        {"id": 298, "name": "Dorri", "email": "Radenhurst"},
        {"id": 299, "name": "Jeremiah", "email": "Room"},
        {"id": 300, "name": "Marcelline", "email": "Laugherane"},
        {"id": 301, "name": "Candie", "email": "Eade"},
        {"id": 302, "name": "Artemas", "email": "Borrington"},
        {"id": 303, "name": "Abramo", "email": "Mathevon"},
        {"id": 304, "name": "Lorinda", "email": "Connick"},
        {"id": 305, "name": "Tresa", "email": "Licciardi"},
        {"id": 306, "name": "Zared", "email": "Chadband"},
        {"id": 307, "name": "Pavel", "email": "Philpotts"},
        {"id": 308, "name": "Vina", "email": "Foulstone"},
        {"id": 309, "name": "Tate", "email": "Gouck"},
        {"id": 310, "name": "Johannes", "email": "Handsheart"},
        {"id": 311, "name": "Lefty", "email": "Dinnington"},
        {"id": 312, "name": "Vittorio", "email": "Brownfield"},
        {"id": 313, "name": "Cyndy", "email": "Dominique"},
        {"id": 314, "name": "Liva", "email": "McKane"},
        {"id": 315, "name": "Wilburt", "email": "Mahaddie"},
        {"id": 316, "name": "Raine", "email": "Renfield"},
        {"id": 317, "name": "Thurstan", "email": "Jest"},
        {"id": 318, "name": "Gael", "email": "MacAlester"},
        {"id": 319, "name": "Halley", "email": "Gaymar"},
        {"id": 320, "name": "Burk", "email": "Heaps"},
        {"id": 321, "name": "Noellyn", "email": "Lichtfoth"},
        {"id": 322, "name": "Burke", "email": "Roiz"},
        {"id": 323, "name": "Felicdad", "email": "Valiant"},
        {"id": 324, "name": "Urson", "email": "Aspin"},
        {"id": 325, "name": "Shirlene", "email": "Crawshaw"},
        {"id": 326, "name": "Jere", "email": "Fawcitt"},
        {"id": 327, "name": "Adan", "email": "Abramchik"},
        {"id": 328, "name": "Neile", "email": "Pigney"},
        {"id": 329, "name": "Nonnah", "email": "Jewer"},
        {"id": 330, "name": "Kris", "email": "Swiffan"},
        {"id": 331, "name": "Debee", "email": "Hibbart"},
        {"id": 332, "name": "Lindsey", "email": "Tarren"},
        {"id": 333, "name": "Jeanine", "email": "Cleary"},
        {"id": 334, "name": "Abe", "email": "Ragsdale"},
        {"id": 335, "name": "Marty", "email": "Lodo"},
        {"id": 336, "name": "Martie", "email": "Serjent"},
        {"id": 337, "name": "Erma", "email": "Hallworth"},
        {"id": 338, "name": "Shannah", "email": "Vamplew"},
        {"id": 339, "name": "Risa", "email": "Roseblade"},
        {"id": 340, "name": "Davie", "email": "Swin"},
        {"id": 341, "name": "Sidney", "email": "Kretschmer"},
        {"id": 342, "name": "Salvador", "email": "Orr"},
        {"id": 343, "name": "Winnie", "email": "Haquin"},
        {"id": 344, "name": "Renato", "email": "Wileman"},
        {"id": 345, "name": "Rozele", "email": "Phippard"},
        {"id": 346, "name": "Allissa", "email": "Bleakley"},
        {"id": 347, "name": "Lynn", "email": "Rape"},
        {"id": 348, "name": "Gabrila", "email": "Bustard"},
        {"id": 349, "name": "Fidelio", "email": "Emmett"},
        {"id": 350, "name": "Jilli", "email": "Goodwins"},
        {"id": 351, "name": "Esra", "email": "Chittey"},
        {"id": 352, "name": "Libby", "email": "McKag"},
        {"id": 353, "name": "Jorge", "email": "Allkins"},
        {"id": 354, "name": "Cobb", "email": "Dunseith"},
        {"id": 355, "name": "Eugenie", "email": "Merrison"},
        {"id": 356, "name": "Caryn", "email": "Rudledge"},
        {"id": 357, "name": "Twila", "email": "Yannoni"},
        {"id": 358, "name": "Barron", "email": "Wingham"},
        {"id": 359, "name": "Dorella", "email": "Brusin"},
        {"id": 360, "name": "Isak", "email": "Aldrich"},
        {"id": 361, "name": "Miof mela", "email": "Betjeman"},
        {"id": 362, "name": "Avram", "email": "Manthorpe"},
        {"id": 363, "name": "Tresa", "email": "Bauduin"},
        {"id": 364, "name": "Doretta", "email": "Carrel"},
        {"id": 365, "name": "Corey", "email": "Flicker"},
        {"id": 366, "name": "Gav", "email": "Orkney"},
        {"id": 367, "name": "Kalinda", "email": "Meiklam"},
        {"id": 368, "name": "Bethina", "email": "Cords"},
        {"id": 369, "name": "Morry", "email": "Owlner"},
        {"id": 370, "name": "Mala", "email": "Harman"},
        {"id": 371, "name": "Essie", "email": "Maxwell"},
        {"id": 372, "name": "Lainey", "email": "Eakens"},
        {"id": 373, "name": "Irena", "email": "Jerdon"},
        {"id": 374, "name": "Connor", "email": "Roz"},
        {"id": 375, "name": "Mellisent", "email": "Rhyme"},
        {"id": 376, "name": "Ali", "email": "Blesdill"},
        {"id": 377, "name": "Dael", "email": "Dmitrievski"},
        {"id": 378, "name": "Edsel", "email": "Swindells"},
        {"id": 379, "name": "Dorthea", "email": "Haley"},
        {"id": 380, "name": "Melosa", "email": "Linstead"},
        {"id": 381, "name": "Sheilah", "email": "Tollerton"},
        {"id": 382, "name": "Roanna", "email": "Darnbrough"},
        {"id": 383, "name": "Reginald", "email": "Surmeyers"},
        {"id": 384, "name": "Jessi", "email": "Measen"},
        {"id": 385, "name": "Damian", "email": "Doudney"},
        {"id": 386, "name": "Temp", "email": "Aubry"},
        {"id": 387, "name": "Eduino", "email": "Garwill"},
        {"id": 388, "name": "Moishe", "email": "Linskill"},
        {"id": 389, "name": "Roderic", "email": "Warbey"},
        {"id": 390, "name": "Irwinn", "email": "Wotherspoon"},
        {"id": 391, "name": "Thain", "email": "Lovatt"},
        {"id": 392, "name": "Shela", "email": "Pontin"},
        {"id": 393, "name": "Doris", "email": "Howsley"},
        {"id": 394, "name": "Caldwell", "email": "Shimwell"},
        {"id": 395, "name": "Conchita", "email": "Polon"},
        {"id": 396, "name": "Flossy", "email": "Trebbett"},
        {"id": 397, "name": "Gabi", "email": "Veart"},
        {"id": 398, "name": "Dallis", "email": "Le Grys"},
        {"id": 399, "name": "Niki", "email": "Britt"},
        {"id": 400, "name": "Paige", "email": "Suggitt"},
        {"id": 401, "name": "Emmye", "email": "Pucker"},
        {"id": 402, "name": "Donna", "email": "Lomasny"},
        {"id": 403, "name": "Fredelia", "email": "Aberhart"},
        {"id": 404, "name": "Cacilia", "email": "Gouldeby"},
        {"id": 405, "name": "Petey", "email": "Angier"},
        {"id": 406, "name": "Putnam", "email": "Lunney"},
        {"id": 407, "name": "Abbie", "email": "Dreini"},
        {"id": 408, "name": "Saleem", "email": "Gaule"},
        {"id": 409, "name": "Man", "email": "Leile"},
        {"id": 410, "name": "Lyda", "email": "Baptist"},
        {"id": 411, "name": "Diana", "email": "Doudney"},
        {"id": 412, "name": "Thom", "email": "Ginie"},
        {"id": 413, "name": "Eleonore", "email": "Thwaite"},
        {"id": 414, "name": "Dominique", "email": "Hawford"},
        {"id": 415, "name": "Wilbur", "email": "Rushe"},
        {"id": 416, "name": "Inigo", "email": "Harraway"},
        {"id": 417, "name": "Malynda", "email": "Vinsen"},
        {"id": 418, "name": "Xena", "email": "LAbbet"},
        {"id": 419, "name": "Hymie", "email": "Filippyev"},
        {"id": 420, "name": "Kirstyn", "email": "Brian"},
        {"id": 421, "name": "Leta", "email": "Boerder"},
        {"id": 422, "name": "Kristy", "email": "Gethings"},
        {"id": 423, "name": "Tommie", "email": "Leftwich"},
        {"id": 424, "name": "Grissel", "email": "McLewd"},
        {"id": 425, "name": "Gianna", "email": "Ocheltree"},
        {"id": 426, "name": "Joanna", "email": "Millen"},
        {"id": 427, "name": "Mikel", "email": "Mathet"},
        {"id": 428, "name": "Fiona", "email": "Conelly"},
        {"id": 429, "name": "Jesselyn", "email": "Fleet"},
        {"id": 430, "name": "Tina", "email": "Whitesel"},
        {"id": 431, "name": "Becky", "email": "Raubenheimer"},
        {"id": 432, "name": "Nathalie", "email": "Oliva"},
        {"id": 433, "name": "Dino", "email": "Saines"},
        {"id": 434, "name": "Clair", "email": "Row"},
        {"id": 435, "name": "Fred", "email": "Tumielli"},
        {"id": 436, "name": "Aharon", "email": "Lambot"},
        {"id": 437, "name": "Daffie", "email": "Ambler"},
        {"id": 438, "name": "Ransell", "email": "Shoard"},
        {"id": 439, "name": "Connie", "email": "Occleshaw"},
        {"id": 440, "name": "Erna", "email": "Extall"},
        {"id": 441, "name": "Oswald", "email": "Bagworth"},
        {"id": 442, "name": "Antonius", "email": "Hynd"},
        {"id": 443, "name": "Earl", "email": "Tidball"},
        {"id": 444, "name": "Bettina", "email": "Snashall"},
        {"id": 445, "name": "Gilbertina", "email": "Hugnet"},
        {"id": 446, "name": "Yoko", "email": "Lummasana"},
        {"id": 447, "name": "Arlene", "email": "O'Collopy"},
        {"id": 448, "name": "Karole", "email": "Lanfear"},
        {"id": 449, "name": "Cati", "email": "Dishmon"},
        {"id": 450, "name": "Marten", "email": "Scotney"},
        {"id": 451, "name": "Jacynth", "email": "Lyness"},
        {"id": 452, "name": "Gherardo", "email": "Nouch"},
        {"id": 453, "name": "Kirstyn", "email": "Freak"},
        {"id": 454, "name": "Quintilla", "email": "Ewbanks"},
        {"id": 455, "name": "Ester", "email": "Tofanelli"},
        {"id": 456, "name": "Dory", "email": "Delacourt"},
        {"id": 457, "name": "Shir", "email": "Darrell"},
        {"id": 458, "name": "Jose", "email": "McCaighey"},
        {"id": 459, "name": "Veronique", "email": "Dimond"},
        {"id": 460, "name": "Morgen", "email": "Schoular"},
        {"id": 461, "name": "Arnold", "email": "Falkinder"},
        {"id": 462, "name": "Phylys", "email": "Lamming"},
        {"id": 463, "name": "Katrine", "email": "Happer"},
        {"id": 464, "name": "Leif", "email": "Fenby"},
        {"id": 465, "name": "Coralie", "email": "Domek"},
        {"id": 466, "name": "Tina", "email": "Burwin"},
        {"id": 467, "name": "Hephzibah", "email": "Pawfoot"},
        {"id": 468, "name": "Avrom", "email": "Withrop"},
        {"id": 469, "name": "Gisela", "email": "Joscelyn"},
        {"id": 470, "name": "Antoinette", "email": "Mattson"},
        {"id": 471, "name": "Lisabeth", "email": "Bownde"},
        {"id": 472, "name": "Austen", "email": "Flukes"},
        {"id": 473, "name": "Petronilla", "email": "Axel"},
        {"id": 474, "name": "Anselma", "email": "MacDermid"},
        {"id": 475, "name": "Brion", "email": "Heis"},
        {"id": 476, "name": "Marget", "email": "Simmins"},
        {"id": 477, "name": "Adella", "email": "Jackes"},
        {"id": 478, "name": "Stu", "email": "Jeppe"},
        {"id": 479, "name": "Hartwell", "email": "Sealove"},
        {"id": 480, "name": "Anitra", "email": "Bawcock"},
        {"id": 481, "name": "Mirabelle", "email": "Gorrie"},
        {"id": 482, "name": "Wittie", "email": "Sweeny"},
        {"id": 483, "name": "Brnaby", "email": "Matteacci"},
        {"id": 484, "name": "Sherline", "email": "Eddicott"},
        {"id": 485, "name": "Lyon", "email": "Mulqueen"},
        {"id": 486, "name": "Marjorie", "email": "Di Baudi"},
        {"id": 487, "name": "Noell", "email": "D'Enrico"},
        {"id": 488, "name": "Forest", "email": "Boschmann"},
        {"id": 489, "name": "Haslett", "email": "Whitty"},
        {"id": 490, "name": "Kacy", "email": "Kentwell"},
        {"id": 491, "name": "Adelice", "email": "Dulwich"},
        {"id": 492, "name": "Dorelle", "email": "Druitt"},
        {"id": 493, "name": "Brigg", "email": "Kilborn"},
        {"id": 494, "name": "Savina", "email": "Phippard"},
        {"id": 495, "name": "Helen", "email": "Barge"},
        {"id": 496, "name": "Shannah", "email": "Leddie"},
        {"id": 497, "name": "Jarrett", "email": "Giddens"},
        {"id": 498, "name": "Libbi", "email": "Kemp"},
        {"id": 499, "name": "Madelina", "email": "Branno"},
        {"id": 500, "name": "Duky", "email": "Awde"},
        {"id": 501, "name": "Ray", "email": "Hitchens"},
        {"id": 502, "name": "Colline", "email": "Riatt"},
        {"id": 503, "name": "Emmerich", "email": "Malham"},
        {"id": 504, "name": "Kevyn", "email": "Davidovich"},
        {"id": 505, "name": "Tobe", "email": "Braddock"},
        {"id": 506, "name": "Bobinette", "email": "Howood"},
        {"id": 507, "name": "Miquela", "email": "Davies"},
        {"id": 508, "name": "Katya", "email": "Baccup"},
        {"id": 509, "name": "Niall", "email": "Bedlington"},
        {"id": 510, "name": "Carmelita", "email": "Usher"},
        {"id": 511, "name": "Sileas", "email": "Philps"},
        {"id": 512, "name": "Odelia", "email": "Gilbard"},
        {"id": 513, "name": "Barron", "email": "Stanfield"},
        {"id": 514, "name": "Ashely", "email": "Bazire"},
        {"id": 515, "name": "Christalle", "email": "Vink"},
        {"id": 516, "name": "Stevena", "email": "Wrist"},
        {"id": 517, "name": "Ted", "email": "Pollard"},
        {"id": 518, "name": "Deina", "email": "Bynold"},
        {"id": 519, "name": "Desirae", "email": "Beau"},
        {"id": 520, "name": "Randie", "email": "Palleske"},
        {"id": 521, "name": "Griselda", "email": "Larham"},
        {"id": 522, "name": "Natividad", "email": "Wycherley"},
        {"id": 523, "name": "Jervis", "email": "Sparham"},
        {"id": 524, "name": "Silvano", "email": "Fortun"},
        {"id": 525, "name": "Emeline", "email": "Bercher"},
        {"id": 526, "name": "Meg", "email": "Durning"},
        {"id": 527, "name": "Maiga", "email": "Bough"},
        {"id": 528, "name": "Toma", "email": "Huburn"},
        {"id": 529, "name": "Pedro", "email": "Bellord"},
        {"id": 530, "name": "Mendie", "email": "Raincin"},
        {"id": 531, "name": "Caye", "email": "Kilfeder"},
        {"id": 532, "name": "Meghan", "email": "Griston"},
        {"id": 533, "name": "Emmi", "email": "Coddrington"},
        {"id": 534, "name": "Seth", "email": "Pendrigh"},
        {"id": 535, "name": "Darla", "email": "McGilbon"},
        {"id": 536, "name": "Gabriel", "email": "Swale"},
        {"id": 537, "name": "Carrie", "email": "Ayres"},
        {"id": 538, "name": "Lyon", "email": "Rudall"},
        {"id": 539, "name": "Sibeal", "email": "Newvill"},
        {"id": 540, "name": "Viviene", "email": "Westfalen"},
        {"id": 541, "name": "Greer", "email": "Davidowich"},
        {"id": 542, "name": "Bordy", "email": "Dunbabin"},
        {"id": 543, "name": "Roxy", "email": "Addams"},
        {"id": 544, "name": "Lowell", "email": "Tatnell"},
        {"id": 545, "name": "Leoline", "email": "Guyonneau"},
        {"id": 546, "name": "Alia", "email": "Johanchon"},
        {"id": 547, "name": "Tommy", "email": "Le Grand"},
        {"id": 548, "name": "Tybi", "email": "Lampart"},
        {"id": 549, "name": "Willyt", "email": "Guisler"},
        {"id": 550, "name": "Otto", "email": "Blood"},
        {"id": 551, "name": "Ludovika", "email": "Todhunter"},
        {"id": 552, "name": "Audrye", "email": "Iorizzo"},
        {"id": 553, "name": "Gypsy", "email": "Kennan"},
        {"id": 554, "name": "Chantalle", "email": "Zylberdik"},
        {"id": 555, "name": "Shaughn", "email": "Dowley"},
        {"id": 556, "name": "Ellswerth", "email": "Hassin"},
        {"id": 557, "name": "Margaret", "email": "Server"},
        {"id": 558, "name": "Nickie", "email": "McEniry"},
        {"id": 559, "name": "Evelyn", "email": "Stillmann"},
        {"id": 560, "name": "Sadie", "email": "Legister"},
        {"id": 561, "name": "Farrel", "email": "Legge"},
        {"id": 562, "name": "Erek", "email": "Dacke"},
        {"id": 563, "name": "Trina", "email": "Duigenan"},
        {"id": 564, "name": "Fowler", "email": "Willetts"},
        {"id": 565, "name": "Gale", "email": "Mauvin"},
        {"id": 566, "name": "Annabelle", "email": "Splain"},
        {"id": 567, "name": "Crystal", "email": "Ardron"},
        {"id": 568, "name": "Lyda", "email": "Pioch"},
        {"id": 569, "name": "Doretta", "email": "Worgen"},
        {"id": 570, "name": "Zach", "email": "Sandifer"},
        {"id": 571, "name": "Bellanca", "email": "Steggals"},
        {"id": 572, "name": "Jermain", "email": "Itzakson"},
        {"id": 573, "name": "Brandyn", "email": "Pegram"},
        {"id": 574, "name": "Sasha", "email": "Iacomo"},
        {"id": 575, "name": "Gian", "email": "Mowat"},
        {"id": 576, "name": "Tedman", "email": "Denk"},
        {"id": 577, "name": "Merwin", "email": "Giorgi"},
        {"id": 578, "name": "Cirstoforo", "email": "Prickett"},
        {"id": 579, "name": "Mateo", "email": "Haster"},
        {"id": 580, "name": "Paulo", "email": "Sans"},
        {"id": 581, "name": "Julio", "email": "Gammons"},
        {"id": 582, "name": "Parry", "email": "Dittson"},
        {"id": 583, "name": "Rhetta", "email": "Harker"},
        {"id": 584, "name": "Laurent", "email": "Toombes"},
        {"id": 585, "name": "Sheffield", "email": "Hanrahan"},
        {"id": 586, "name": "Mei", "email": "Ashbe"},
        {"id": 587, "name": "Madelaine", "email": "Brenton"},
        {"id": 588, "name": "Hashim", "email": "Neller"},
        {"id": 589, "name": "Sibylla", "email": "Croisier"},
        {"id": 590, "name": "Peri", "email": "Saffe"},
        {"id": 591, "name": "Chantal", "email": "Oby"},
        {"id": 592, "name": "Miller", "email": "Stodhart"},
        {"id": 593, "name": "Selig", "email": "Carcass"},
        {"id": 594, "name": "Demott", "email": "Kenton"},
        {"id": 595, "name": "Cecile", "email": "de Clerq"},
        {"id": 596, "name": "Alden", "email": "Stead"},
        {"id": 597, "name": "Clywd", "email": "Armytage"},
        {"id": 598, "name": "Inger", "email": "Hucke"},
        {"id": 599, "name": "Winslow", "email": "Jee"},
        {"id": 600, "name": "Emma", "email": "Alden"},
        {"id": 601, "name": "Arluene", "email": "Fowlestone"},
        {"id": 602, "name": "Maitilde", "email": "Kindley"},
        {"id": 603, "name": "Lindsy", "email": "Joris"},
        {"id": 604, "name": "Gabi", "email": "Rentelll"},
        {"id": 605, "name": "Wendy", "email": "Haszard"},
        {"id": 606, "name": "Asa", "email": "Isac"},
        {"id": 607, "name": "Shem", "email": "Jirzik"},
        {"id": 608, "name": "Randee", "email": "McKim"},
        {"id": 609, "name": "Humberto", "email": "Chrippes"},
        {"id": 610, "name": "Gay", "email": "Agates"},
        {"id": 611, "name": "Arthur", "email": "Arendsen"},
        {"id": 612, "name": "Beulah", "email": "Shieber"},
        {"id": 613, "name": "Helenelizabeth", "email": "Falconer"},
        {"id": 614, "name": "Gizela", "email": "Critoph"},
        {"id": 615, "name": "Isahella", "email": "Domel"},
        {"id": 616, "name": "Eliza", "email": "Stanford"},
        {"id": 617, "name": "Adda", "email": "Hannibal"},
        {"id": 618, "name": "Godard", "email": "Olechnowicz"},
        {"id": 619, "name": "Julietta", "email": "Bourges"},
        {"id": 620, "name": "Richardo", "email": "Ballaam"},
        {"id": 621, "name": "Bronnie", "email": "Darkins"},
        {"id": 622, "name": "Zacharia", "email": "Salvadori"},
        {"id": 623, "name": "Wilone", "email": "Pritchard"},
        {"id": 624, "name": "Daniella", "email": "Wallege"},
        {"id": 625, "name": "Marylynne", "email": "Garrit"},
        {"id": 626, "name": "Ebenezer", "email": "Sherrocks"},
        {"id": 627, "name": "Candis", "email": "Stanett"},
        {"id": 628, "name": "Rivi", "email": "Goldhill"},
        {"id": 629, "name": "Lucien", "email": "Huggett"},
        {"id": 630, "name": "Farr", "email": "Tierney"},
        {"id": 631, "name": "Sophi", "email": "Thames"},
        {"id": 632, "name": "Cy", "email": "Thalmann"},
        {"id": 633, "name": "Loria", "email": "Duddy"},
        {"id": 634, "name": "Belita", "email": "Jimpson"},
        {"id": 635, "name": "Valene", "email": "Elgey"},
        {"id": 636, "name": "Clarence", "email": "Curman"},
        {"id": 637, "name": "Wren", "email": "Bleibaum"},
        {"id": 638, "name": "Avery", "email": "Draper"},
        {"id": 639, "name": "Charis", "email": "Peetermann"},
        {"id": 640, "name": "Rosalinda", "email": "Sinney"},
        {"id": 641, "name": "Kiley", "email": "Jenkison"},
        {"id": 642, "name": "Mac", "email": "Jobe"},
        {"id": 643, "name": "Griselda", "email": "Gonnet"},
        {"id": 644, "name": "Catherine", "email": "Gerty"},
        {"id": 645, "name": "Kristoforo", "email": "Bremner"},
        {"id": 646, "name": "Theresita", "email": "Cockell"},
        {"id": 647, "name": "Miguela", "email": "Yakunin"},
        {"id": 648, "name": "Leandra", "email": "Worswick"},
        {"id": 649, "name": "Sally", "email": "Discombe"},
        {"id": 650, "name": "Tiffi", "email": "Elnaugh"},
        {"id": 651, "name": "Stefan", "email": "Klossmann"},
        {"id": 652, "name": "Bay", "email": "Cayle"},
        {"id": 653, "name": "Greta", "email": "Lathom"},
        {"id": 654, "name": "Rafe", "email": "Dinning"},
        {"id": 655, "name": "Joyann", "email": "Bunten"},
        {"id": 656, "name": "Salomon", "email": "Cuthbertson"},
        {"id": 657, "name": "Cecilla", "email": "Noakes"},
        {"id": 658, "name": "Leigh", "email": "Blaylock"},
        {"id": 659, "name": "Sofia", "email": "Roxburch"},
        {"id": 660, "name": "Lorrie", "email": "Parmley"},
        {"id": 661, "name": "Franchot", "email": "Brattan"},
        {"id": 662, "name": "Janos", "email": "Mathews"},
        {"id": 663, "name": "Ronica", "email": "Barthrup"},
        {"id": 664, "name": "Derrick", "email": "O' Neligan"},
        {"id": 665, "name": "Bale", "email": "Hissett"},
        {"id": 666, "name": "Anastasia", "email": "Haig"},
        {"id": 667, "name": "Arabele", "email": "Andras"},
        {"id": 668, "name": "Audry", "email": "O' Gara"},
        {"id": 669, "name": "Ezechiel", "email": "Fladgate"},
        {"id": 670, "name": "Faustina", "email": "Probyn"},
        {"id": 671, "name": "Gregorius", "email": "Jarrett"},
        {"id": 672, "name": "Hyman", "email": "Ewbanke"},
        {"id": 673, "name": "Major", "email": "Kraut"},
        {"id": 674, "name": "Valenka", "email": "Wearing"},
        {"id": 675, "name": "Jaclin", "email": "Tilburn"},
        {"id": 676, "name": "Jackquelin", "email": "Milkin"},
        {"id": 677, "name": "Noland", "email": "Bwye"},
        {"id": 678, "name": "Carma", "email": "Putnam"},
        {"id": 679, "name": "Cole", "email": "Zoellner"},
        {"id": 680, "name": "Fayette", "email": "Bradborne"},
        {"id": 681, "name": "Zilvia", "email": "Larter"},
        {"id": 682, "name": "Geri", "email": "Cheney"},
        {"id": 683, "name": "Cari", "email": "Gorbell"},
        {"id": 684, "name": "Trudie", "email": "Pennetta"},
        {"id": 685, "name": "Alon", "email": "Teggart"},
        {"id": 686, "name": "Fanny", "email": "Meyer"},
        {"id": 687, "name": "Giselbert", "email": "Dilliston"},
        {"id": 688, "name": "Gabriele", "email": "Ingliby"},
        {"id": 689, "name": "Tonye", "email": "Worvill"},
        {"id": 690, "name": "Moise", "email": "Yantsev"},
        {"id": 691, "name": "Gaylene", "email": "Hassekl"},
        {"id": 692, "name": "Giffie", "email": "Gaskoin"},
        {"id": 693, "name": "Rees", "email": "Copello"},
        {"id": 694, "name": "Cassandra", "email": "Rubinsohn"},
        {"id": 695, "name": "Cchaddie", "email": "Yurukhin"},
        {"id": 696, "name": "Sharron", "email": "Pavlik"},
        {"id": 697, "name": "Elissa", "email": "O'Halligan"},
        {"id": 698, "name": "Harmonie", "email": "Diplock"},
        {"id": 699, "name": "Murry", "email": "Steggals"},
        {"id": 700, "name": "Donnie", "email": "Coppock."},
        {"id": 701, "name": "Tarra", "email": "Jakubiak"},
        {"id": 702, "name": "Mikael", "email": "Gossington"},
        {"id": 703, "name": "Roxy", "email": "Sainer"},
        {"id": 704, "name": "Hussein", "email": "Fruchter"},
        {"id": 705, "name": "Chase", "email": "Kinson"},
        {"id": 706, "name": "Silvain", "email": "Karlmann"},
        {"id": 707, "name": "Lawry", "email": "Velte"},
        {"id": 708, "name": "Herb", "email": "Oaten"},
        {"id": 709, "name": "Melessa", "email": "Columbell"},
        {"id": 710, "name": "Allyce", "email": "Wyles"},
        {"id": 711, "name": "Vasilis", "email": "Rodear"},
        {"id": 712, "name": "Mic", "email": "Folan"},
        {"id": 713, "name": "Elianore", "email": "Glading"},
        {"id": 714, "name": "Margi", "email": "Piddle"},
        {"id": 715, "name": "Ashien", "email": "Grishaev"},
        {"id": 716, "name": "Lucio", "email": "Westbury"},
        {"id": 717, "name": "Felicdad", "email": "Willoughby"},
        {"id": 718, "name": "Aurthur", "email": "Nelthropp"},
        {"id": 719, "name": "Megen", "email": "Hayen"},
        {"id": 720, "name": "Zsazsa", "email": "Palin"},
        {"id": 721, "name": "Norine", "email": "Pettigrew"},
        {"id": 722, "name": "Bryanty", "email": "Blackborn"},
        {"id": 723, "name": "Corby", "email": "Southway"},
        {"id": 724, "name": "Shelton", "email": "Musgrove"},
        {"id": 725, "name": "Jodie", "email": "Bartholat"},
        {"id": 726, "name": "Everett", "email": "Critchlow"},
        {"id": 727, "name": "Valentia", "email": "Officer"},
        {"id": 728, "name": "Evangelin", "email": "Godlee"},
        {"id": 729, "name": "Ethelbert", "email": "Faragher"},
        {"id": 730, "name": "Clary", "email": "Easterbrook"},
        {"id": 731, "name": "Filippa", "email": "Drillot"},
        {"id": 732, "name": "Kirsten", "email": "Shank"},
        {"id": 733, "name": "Lilli", "email": "Comsty"},
        {"id": 734, "name": "Marika", "email": "Courtliff"},
        {"id": 735, "name": "Haleigh", "email": "Flucker"},
        {"id": 736, "name": "Katharina", "email": "Purcer"},
        {"id": 737, "name": "Bradly", "email": "Northwood"},
        {"id": 738, "name": "Westley", "email": "Kuhne"},
        {"id": 739, "name": "Heath", "email": "Jobey"},
        {"id": 740, "name": "Kordula", "email": "Velasquez"},
        {"id": 741, "name": "Welch", "email": "Pestridge"},
        {"id": 742, "name": "Nollie", "email": "Colbran"},
        {"id": 743, "name": "Hank", "email": "Muskett"},
        {"id": 744, "name": "Wendall", "email": "Bohey"},
        {"id": 745, "name": "Flossi", "email": "Riddeough"},
        {"id": 746, "name": "Portia", "email": "Van der Kruys"},
        {"id": 747, "name": "Andrea", "email": "Hainey`"},
        {"id": 748, "name": "Trixi", "email": "Crat"},
        {"id": 749, "name": "Mel", "email": "Negus"},
        {"id": 750, "name": "Janette", "email": "Georgot"},
        {"id": 751, "name": "Shep", "email": "Tuvey"},
        {"id": 752, "name": "Dan", "email": "Naisey"},
        {"id": 753, "name": "Irina", "email": "Fredi"},
        {"id": 754, "name": "Link", "email": "Mustoo"},
        {"id": 755, "name": "Ketti", "email": "Strank"},
        {"id": 756, "name": "Frayda", "email": "Bradnick"},
        {"id": 757, "name": "Sauncho", "email": "Beadnall"},
        {"id": 758, "name": "Jone", "email": "Sidey"},
        {"id": 759, "name": "Christal", "email": "Mossop"},
        {"id": 760, "name": "Skelly", "email": "Matthiae"},
        {"id": 761, "name": "Nikolaus", "email": "Croix"},
        {"id": 762, "name": "Lemar", "email": "Howatt"},
        {"id": 763, "name": "Avril", "email": "Pipping"},
        {"id": 764, "name": "Roma", "email": "Waring"},
        {"id": 765, "name": "Yurik", "email": "Durrand"},
        {"id": 766, "name": "Ari", "email": "Tottle"},
        {"id": 767, "name": "Kelsy", "email": "Bodicam"},
        {"id": 768, "name": "Lu", "email": "Polle"},
        {"id": 769, "name": "Prentiss", "email": "Keer"},
        {"id": 770, "name": "Archibold", "email": "Connachan"},
        {"id": 771, "name": "Wandis", "email": "Hegg"},
        {"id": 772, "name": "Raquel", "email": "Hammerman"},
        {"id": 773, "name": "Eliza", "email": "Stent"},
        {"id": 774, "name": "Terry", "email": "Coast"},
        {"id": 775, "name": "Kelwin", "email": "Boys"},
        {"id": 776, "name": "Ethelyn", "email": "Sandcroft"},
        {"id": 777, "name": "Bordy", "email": "Feild"},
        {"id": 778, "name": "Wilt", "email": "Durrell"},
        {"id": 779, "name": "Alene", "email": "Combe"},
        {"id": 780, "name": "Teena", "email": "Cheine"},
        {"id": 781, "name": "Virgina", "email": "Wimbush"},
        {"id": 782, "name": "Wanids", "email": "Sampson"},
        {"id": 783, "name": "Heddi", "email": "Fance"},
        {"id": 784, "name": "Micki", "email": "Brunel"},
        {"id": 785, "name": "Gilberte", "email": "O'Cahill"},
        {"id": 786, "name": "Marthe", "email": "Ossenna"},
        {"id": 787, "name": "Jacquelin", "email": "Sworder"},
        {"id": 788, "name": "Jenda", "email": "Pinson"},
        {"id": 789, "name": "Ruben", "email": "Winfindale"},
        {"id": 790, "name": "Alis", "email": "Easby"},
        {"id": 791, "name": "Carin", "email": "Mullord"},
        {"id": 792, "name": "Cary", "email": "de Voiels"},
        {"id": 793, "name": "Isabella", "email": "Medlar"},
        {"id": 794, "name": "Benedick", "email": "Slaughter"},
        {"id": 795, "name": "Danny", "email": "Braunroth"},
        {"id": 796, "name": "Poppy", "email": "Duggon"},
        {"id": 797, "name": "Heloise", "email": "De Few"},
        {"id": 798, "name": "Chan", "email": "Zuanazzi"},
        {"id": 799, "name": "Tim", "email": "Penvarden"},
        {"id": 800, "name": "Mick", "email": "Kissell"},
        {"id": 801, "name": "Zach", "email": "Woodyatt"},
        {"id": 802, "name": "Archibold", "email": "Defont"},
        {"id": 803, "name": "Arty", "email": "Mayall"},
        {"id": 804, "name": "Shirline", "email": "Sides"},
        {"id": 805, "name": "Persis", "email": "Behr"},
        {"id": 806, "name": "Rhetta", "email": "Chable"},
        {"id": 807, "name": "Amanda", "email": "Cavil"},
        {"id": 808, "name": "Tessa", "email": "Goode"},
        {"id": 809, "name": "Derry", "email": "Bouzek"},
        {"id": 810, "name": "Cris", "email": "Priestland"},
        {"id": 811, "name": "Cari", "email": "Gutcher"},
        {"id": 812, "name": "Edie", "email": "Gollop"},
        {"id": 813, "name": "Merilyn", "email": "Matoshin"},
        {"id": 814, "name": "Asher", "email": "Fulmen"},
        {"id": 815, "name": "Valentine", "email": "Bondar"},
        {"id": 816, "name": "Leighton", "email": "Surgenor"},
        {"id": 817, "name": "Culley", "email": "Borlease"},
        {"id": 818, "name": "Janene", "email": "Armstrong"},
        {"id": 819, "name": "Carlotta", "email": "Curphey"},
        {"id": 820, "name": "Eal", "email": "Dumphries"},
        {"id": 821, "name": "Simonette", "email": "Kiera"},
        {"id": 822, "name": "Anthia", "email": "Ferro"},
        {"id": 823, "name": "Nancy", "email": "Vahey"},
        {"id": 824, "name": "Arney", "email": "MacKegg"},
        {"id": 825, "name": "Marnia", "email": "O'Shaughnessy"},
        {"id": 826, "name": "Rycca", "email": "Harmond"},
        {"id": 827, "name": "Marcie", "email": "Lovie"},
        {"id": 828, "name": "Evyn", "email": "Cassam"},
        {"id": 829, "name": "Evyn", "email": "Fillary"},
        {"id": 830, "name": "Myrtle", "email": "Ahren"},
        {"id": 831, "name": "Rosemaria", "email": "Darbon"},
        {"id": 832, "name": "Dennis", "email": "Volks"},
        {"id": 833, "name": "Hussein", "email": "Sundin"},
        {"id": 834, "name": "Tannie", "email": "Scaplehorn"},
        {"id": 835, "name": "Edouard", "email": "Drinan"},
        {"id": 836, "name": "Laural", "email": "Cobley"},
        {"id": 837, "name": "Doyle", "email": "Crufts"},
        {"id": 838, "name": "Tamqrah", "email": "Swadling"},
        {"id": 839, "name": "Austina", "email": "McChesney"},
        {"id": 840, "name": "Cordy", "email": "Spiaggia"},
        {"id": 841, "name": "Matthus", "email": "Banstead"},
        {"id": 842, "name": "Nissie", "email": "Egger"},
        {"id": 843, "name": "Katee", "email": "Staples"},
        {"id": 844, "name": "Staford", "email": "Livett"},
        {"id": 845, "name": "Annamaria", "email": "Snuggs"},
        {"id": 846, "name": "Garnet", "email": "Sigars"},
        {"id": 847, "name": "Jehanna", "email": "Morson"},
        {"id": 848, "name": "Sara", "email": "Grishmanov"},
        {"id": 849, "name": "Roderic", "email": "Nanni"},
        {"id": 850, "name": "Fina", "email": "Braam"},
        {"id": 851, "name": "Norean", "email": "Jenteau"},
        {"id": 852, "name": "Charissa", "email": "Onslow"},
        {"id": 853, "name": "Cleo", "email": "Daniaud"},
        {"id": 854, "name": "Orbadiah", "email": "Forseith"},
        {"id": 855, "name": "Stevana", "email": "Moline"},
        {"id": 856, "name": "Bathsheba", "email": "McGarva"},
        {"id": 857, "name": "Beck", "email": "Cowlas"},
        {"id": 858, "name": "Sheila", "email": "Tackell"},
        {"id": 859, "name": "Marius", "email": "Tourville"},
        {"id": 860, "name": "Esmeralda", "email": "Reddish"},
        {"id": 861, "name": "Gabrielle", "email": "Baddam"},
        {"id": 862, "name": "Romy", "email": "Govern"},
        {"id": 863, "name": "Tracee", "email": "Klinck"},
        {"id": 864, "name": "Willdon", "email": "Aughtie"},
        {"id": 865, "name": "Paige", "email": "Boolsen"},
        {"id": 866, "name": "Maritsa", "email": "Giovannacci"},
        {"id": 867, "name": "Rorke", "email": "Biskupek"},
        {"id": 868, "name": "Towny", "email": "Skeldon"},
        {"id": 869, "name": "Orrin", "email": "Ghidoni"},
        {"id": 870, "name": "Agnesse", "email": "Shevlin"},
        {"id": 871, "name": "Tory", "email": "De Dantesie"},
        {"id": 872, "name": "Aida", "email": "Duddell"},
        {"id": 873, "name": "Siegfried", "email": "Vaneschi"},
        {"id": 874, "name": "Dorelle", "email": "Halfpenny"},
        {"id": 875, "name": "Ilario", "email": "Codeman"},
        {"id": 876, "name": "Aleece", "email": "Badcock"},
        {"id": 877, "name": "Marline", "email": "Dwelley"},
        {"id": 878, "name": "Cammie", "email": "Hindmoor"},
        {"id": 879, "name": "Dyana", "email": "Ivannikov"},
        {"id": 880, "name": "Abner", "email": "Hanigan"},
        {"id": 881, "name": "Rawley", "email": "Ruselin"},
        {"id": 882, "name": "Halli", "email": "Sullly"},
        {"id": 883, "name": "Newton", "email": "Ventum"},
        {"id": 884, "name": "Sarita", "email": "Arter"},
        {"id": 885, "name": "Brig", "email": "Dwyer"},
        {"id": 886, "name": "Delainey", "email": "Widger"},
        {"id": 887, "name": "Maudie", "email": "Dzenisenka"},
        {"id": 888, "name": "Valerie", "email": "Dickon"},
        {"id": 889, "name": "Madeline", "email": "Hatherley"},
        {"id": 890, "name": "Noby", "email": "Kierans"},
        {"id": 891, "name": "Galven", "email": "Kearney"},
        {"id": 892, "name": "Iggie", "email": "Dundendale"},
        {"id": 893, "name": "Dixie", "email": "Castle"},
        {"id": 894, "name": "Eliot", "email": "Hugnin"},
        {"id": 895, "name": "Lucia", "email": "Desvignes"},
        {"id": 896, "name": "Luciana", "email": "Linde"},
        {"id": 897, "name": "Hanan", "email": "Bhar"},
        {"id": 898, "name": "Waiter", "email": "Gratland"},
        {"id": 899, "name": "Heywood", "email": "Dudek"},
        {"id": 900, "name": "Meris", "email": "Ost"},
        {"id": 901, "name": "Casie", "email": "Scollan"},
        {"id": 902, "name": "Sammie", "email": "Szabo"},
        {"id": 903, "name": "Bradford", "email": "Wingar"},
        {"id": 904, "name": "Philippa", "email": "Leindecker"},
        {"id": 905, "name": "Cathi", "email": "Jorn"},
        {"id": 906, "name": "Mufi", "email": "Lantuffe"},
        {"id": 907, "name": "Eden", "email": "Brandacci"},
        {"id": 908, "name": "Maurie", "email": "Crowe"},
        {"id": 909, "name": "Dre", "email": "Brokenshaw"},
        {"id": 910, "name": "Padraig", "email": "Beck"},
        {"id": 911, "name": "Chelsea", "email": "Stuehmeier"},
        {"id": 912, "name": "Leroi", "email": "O'Longain"},
        {"id": 913, "name": "Bessy", "email": "Tretwell"},
        {"id": 914, "name": "Sig", "email": "Purry"},
        {"id": 915, "name": "Nilson", "email": "Aldin"},
        {"id": 916, "name": "Bernetta", "email": "Pedreschi"},
        {"id": 917, "name": "Dana", "email": "Janek"},
        {"id": 918, "name": "Mose", "email": "Fontelles"},
        {"id": 919, "name": "Wilfrid", "email": "Sturt"},
        {"id": 920, "name": "Melisenda", "email": "Fortune"},
        {"id": 921, "name": "Kalindi", "email": "Shobrook"},
        {"id": 922, "name": "Steffi", "email": "Traut"},
        {"id": 923, "name": "Eben", "email": "Buddell"},
        {"id": 924, "name": "Georgette", "email": "Shickle"},
        {"id": 925, "name": "Diannne", "email": "Gurg"},
        {"id": 926, "name": "Lukas", "email": "Tremmel"},
        {"id": 927, "name": "Terrell", "email": "Fitzgerald"},
        {"id": 928, "name": "Rhys", "email": "Jerrom"},
        {"id": 929, "name": "Tarra", "email": "Espinet"},
        {"id": 930, "name": "Camey", "email": "Hebard"},
        {"id": 931, "name": "Danice", "email": "Paik"},
        {"id": 932, "name": "Terrie", "email": "Busain"},
        {"id": 933, "name": "Eolande", "email": "Mays"},
        {"id": 934, "name": "Flory", "email": "Gawkes"},
        {"id": 935, "name": "Marys", "email": "Maggorini"},
        {"id": 936, "name": "Kathye", "email": "Janaszewski"},
        {"id": 937, "name": "Lani", "email": "Chalfain"},
        {"id": 938, "name": "Esteban", "email": "Levee"},
        {"id": 939, "name": "Elvina", "email": "Eliot"},
        {"id": 940, "name": "Tyrone", "email": "Dongate"},
        {"id": 941, "name": "Phoebe", "email": "Hablet"},
        {"id": 942, "name": "Brook", "email": "Goater"},
        {"id": 943, "name": "Shir", "email": "Vardey"},
        {"id": 944, "name": "Ezekiel", "email": "Hanaby"},
        {"id": 945, "name": "Christine", "email": "Duncanson"},
        {"id": 946, "name": "Loralee", "email": "de la Tremoille"},
        {"id": 947, "name": "Gale", "email": "Berrow"},
        {"id": 948, "name": "Connie", "email": "Arrell"},
        {"id": 949, "name": "Kaela", "email": "Baccas"},
        {"id": 950, "name": "Michal", "email": "Richardt"},
        {"id": 951, "name": "Dawna", "email": "Scotney"},
        {"id": 952, "name": "Valencia", "email": "Persian"},
        {"id": 953, "name": "Avie", "email": "Lande"},
        {"id": 954, "name": "Tomasine", "email": "McOmish"},
        {"id": 955, "name": "Perceval", "email": "MacKenny"},
        {"id": 956, "name": "Aurlie", "email": "Drennan"},
        {"id": 957, "name": "Natalya", "email": "Snap"},
        {"id": 958, "name": "Marylynne", "email": "Pepperd"},
        {"id": 959, "name": "Letty", "email": "Greenstreet"},
        {"id": 960, "name": "Celestyna", "email": "Grimsdell"},
        {"id": 961, "name": "Rosalinda", "email": "Sneden"},
        {"id": 962, "name": "Annamaria", "email": "Dyas"},
        {"id": 963, "name": "Claudina", "email": "Dowsing"},
        {"id": 964, "name": "Harmonia", "email": "Gosenell"},
        {"id": 965, "name": "Layney", "email": "Cockson"},
        {"id": 966, "name": "Harcourt", "email": "Maken"},
        {"id": 967, "name": "Ludovico", "email": "Duignan"},
        {"id": 968, "name": "Prentice", "email": "Todaro"},
        {"id": 969, "name": "Nike", "email": "Lunney"},
        {"id": 970, "name": "Vinson", "email": "Runacres"},
        {"id": 971, "name": "Harriette", "email": "Onge"},
        {"id": 972, "name": "Helge", "email": "Leamy"},
        {"id": 973, "name": "Odetta", "email": "Merigot"},
        {"id": 974, "name": "Conchita", "email": "Nowick"},
        {"id": 975, "name": "Leanna", "email": "Hamblin"},
        {"id": 976, "name": "Meredith", "email": "Lewsie"},
        {"id": 977, "name": "Maressa", "email": "Ranscomb"},
        {"id": 978, "name": "Chrisse", "email": "Oakenford"},
        {"id": 979, "name": "Ian", "email": "Tothe"},
        {"id": 980, "name": "Lancelot", "email": "Scrauniage"},
        {"id": 981, "name": "Kirbie", "email": "Burnyate"},
        {"id": 982, "name": "Cicily", "email": "Densun"},
        {"id": 983, "name": "Kerwin", "email": "Arpe"},
        {"id": 984, "name": "Dyana", "email": "Casoni"},
        {"id": 985, "name": "Gena", "email": "Hamon"},
        {"id": 986, "name": "Beatrisa", "email": "Clue"},
        {"id": 987, "name": "Harlie", "email": "Handlin"},
        {"id": 988, "name": "Marylou", "email": "Woolway"},
        {"id": 989, "name": "Marcos", "email": "Shilliday"},
        {"id": 990, "name": "Renaud", "email": "Rizzelli"},
        {"id": 991, "name": "Penn", "email": "Decourcy"},
        {"id": 992, "name": "Rich", "email": "Klimowicz"},
        {"id": 993, "name": "Finley", "email": "Dinning"},
        {"id": 994, "name": "Fergus", "email": "Starmer"},
        {"id": 995, "name": "Anette", "email": "Clausen-Thue"},
        {"id": 996, "name": "Xavier", "email": "Persence"},
        {"id": 997, "name": "Eliza", "email": "Annwyl"},
        {"id": 998, "name": "Sara-ann", "email": "Devoy"},
        {"id": 999, "name": "Laurena", "email": "Mordanti"},
        {"id": 1000, "name": "Alexina", "email": "Predohl"},
         {"id": 1001, "name": "dinesh", "email": "dinesh@gmail.com"},
         {"id": 1002, "name": "dinesh", "email": "dinesh@gmail.com"}
      ];

      return data.map((json) => User.fromJson(json)).toList();
    } else {
      throw Exception("Failed to load users");
    }
  }
}

// Main App
void main() => runApp(MaterialApp(home: UserTableScreen()));

class UserTableScreen extends StatefulWidget {
  @override
  _UserTableScreenState createState() => _UserTableScreenState();
}

class _UserTableScreenState extends State<UserTableScreen> {
  late Future<List<User>> _userList;
  final List<User> _localUsers = [];
  TextEditingController searchController = TextEditingController(); // For locally added users
   List<User> filteredItems = [];
  
  @override
  void initState() {
    super.initState();
    _fetchData(); // Initial data fetch
  }

 



 void _fetchData() {
    _userList = ApiService().fetchUsers();
    _userList.then((users) {
      setState(() {
        filteredItems = users; // Initialize filtered items with fetched users
      });
    }).catchError((error) {
      // Handle error if the fetch fails
      print("Error fetching users: $error");
    });
  }

   void _filterItems(String query) {
    query = query.toLowerCase();
    _userList.then((users) {
      setState(() {
        filteredItems = users.where((user) {
          final name = user.name.toLowerCase();
          final email = user.email.toLowerCase();
          return name.contains(query) || email.contains(query);
        }).toList();
      });
    });
  }

  // Method to add a new user locally
  void _addUser(String name, String email) {
    setState(() {
      int newId = _localUsers.isNotEmpty
          ? _localUsers.last.id + 1
          : 11; // New ID for the added user
      _localUsers.add(User(id: newId, name: name, email: email));
    });
    Navigator.of(context).pop(); // Close the dialog
  }

  // Method to show Add User dialog
  void _showAddUserDialog() {
    final nameController = TextEditingController();
    final emailController = TextEditingController();

    showDialog(
      context: context,
      builder: (context) {
        return AlertDialog(
          title: const Text("Add New User"),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              TextField(
                controller: nameController,
                decoration: const InputDecoration(labelText: "Name"),
              ),
              TextField(
                controller: emailController,
                decoration: const InputDecoration(labelText: "Email"),
              ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.of(context).pop(),
              child: const Text("Cancel"),
            ),
            ElevatedButton(
              onPressed: () {
                final name = nameController.text.trim();
                final email = emailController.text.trim();
                if (name.isNotEmpty && email.isNotEmpty) {
                  _addUser(name, email);
                }
              },
              child: const Text("Add"),
            ),
          ],
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("User Details Table"),
          automaticallyImplyLeading: false,
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh), // Add a refresh icon
            onPressed: () {
              _fetchData(); // Fetch data again on button press
            },
          ),
          IconButton(
            icon: const Icon(Icons.add), // Add an "Add" button
            onPressed: _showAddUserDialog, // Show the Add User dialog
          ),
        ],
      ),
      body: Column(
        children: [

          Padding(padding: const EdgeInsets.all(10.0),
          child: Row(
            children:  [
              Expanded(child: TextField(
                 controller: searchController,
                decoration: InputDecoration(
                  labelText: "Search Name and Email",
                   border: OutlineInputBorder(),
                   suffixIcon: IconButton(
                        icon:  Icon(Icons.clear),
                        onPressed: () {
                          searchController.clear();
                          _filterItems(''); 
                          // Clear search and reset items
                        },
                      )


                ),
                 onChanged: _filterItems,
              ))
            ],
          ),
          ),

          Expanded(
            child: SingleChildScrollView(
              child: FutureBuilder<List<User>>(
              future: _userList,
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  // Show a circular loader when the API is being fetched
                  return const Center(child: CircularProgressIndicator());
                } else if (snapshot.hasError) {
                  // Display error message if the API request fails
                  return Center(child: Text("Error: ${snapshot.error}"));
                } else if (!snapshot.hasData || snapshot.data!.isEmpty) {
                  // Handle case when no data is returned
                  return const Center(child: Text("No users found"));
                } else {
                  // Combine API users with local users
                  final allUsers = filteredItems;
                  // print(snapshot.data!.isNotEmpty);
                  // print("snapshot.hasData: ${snapshot.hasData}");
            // print("snapshot.data: ${snapshot.data}");
            // print("Filtered Items Length: ${filteredItems.length}");
                  return snapshot.hasData && !filteredItems.isEmpty ?  PaginatedDataTable(
                    // header: const Text('User Details'),
                    columns: const [
                      DataColumn(label: Text('ID')),
                      DataColumn(label: Text('Name')),
                      DataColumn(label: Text('Email'))
                    ],
                    source: UserDataSource(allUsers),
                    rowsPerPage: 10, // Set the number of rows per page
                  ) : const Center(child: Text("No Users found"),);
                }
              },
            ),
            ),
          ),
        ],
      ),
    );
  }
}

class UserDataSource extends DataTableSource {
  final List<User> users;

  UserDataSource(this.users);

  @override
  DataRow getRow(int index) {
    final user = users[index];
    return DataRow(cells: [
      DataCell(Text(user.id.toString())),
      DataCell(Text(user.name)),
      DataCell(Text(user.email)),
    ]);
  }

  @override
  int get rowCount => users.length;

  @override
  int get selectedRowCount => 0;

  // Add the missing getter for isRowCountApproximate
  @override
  bool get isRowCountApproximate => false;
}
